### ISSUE TITLE
dfrd.when() method progress is not working as expected.

### ISSUE THREAD

**Issue by Sujsun** [Sujsun/Deferred#1]
Deferred object returned by dfrd.when() method should give the overall progress of the given n number of deferred objects.

**Comment by anand-io** [comment]
Is this under development?

**Comment by Sujsun** [comment]
No, doing some research on it.
If you have a solution please share it/push.
Thanks.

**Comment by Sujsun** [comment]
Have to add progress event for when method.

**Comment by anand-io** [comment]
Completed progress for when in this commit c0bc3798511e2e5076b3894c482b016131be6a95
